require_relative 'task'
require_relative 'tasks/cmd_task'
require_relative 'tasks/script_dir'
require_relative 'tasks/watch_folder'
require_relative 'tasks/eval_task'
require_relative 'tasks/rabbitmq'
require_relative 'tasks/mongo_query'
require_relative 'tasks/monitoring/sysmon'
